version: '3'

services:
  nginx-unit:
    build:
      context: ./unit
    ports:
      - 8500:8500
      - 8300:8300
    volumes:
       - ./conf:/root/json
       - ./run:/var/run
       - ./php:/var/www/php
       - go-executable:/www/server/bin
  api:
    build: 
      context: ./api
    ports:
      - 3000:8000
    volumes:
      - go-executable:/go/src/github.com/gcoka/nginx-unit-go-api/build
      - .:/go/src/github.com/gcoka/nginx-unit-go-api
    command: ["make", "start"]

volumes:
  go-executable:
